org: sandeepzgk
app: vtgame-platform
service: core
frameworkVersion: '3'

custom:
  tableName: 'vtgame-data-table-${sls:stage}'
  bucketName: 'vtgame-file-bucket-${sls:stage}'
  dynamodb:
    start:
      migrate: false
    stages:
      - dev  	
  client:
    bucketName: 'vtgame-web-bucket-${sls:stage}'

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 5
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ DataTable, Arn ]
        - Effect: 'Allow'
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
          Resource:
            Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - !Ref StorageBucket
                - '/*'
           

  environment:
    DATA_TABLE: ${self:custom.tableName}
    STORAGE_BUCKET: ${self:custom.bucketName}
    REGION: "us-east-1"
    CLIENT_ID: ${param:GOOG_CLIENT_ID}
    CLIENT_SECRET: ${param:GOOG_CLIENT_SECRET}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    DataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: expid
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: expid
            KeyType: HASH
          - AttributeName: email
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
    StorageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
    
plugins:
  - serverless-finch
